#!/bin/bash
#PBS -P InsulinAnalogs
#PBS -l ngpus=4
#PBS -l ncpus=36
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l mem=8GB
#PBS -M yearlyboozefest@gmail.com
#PBS -q defaultQ

cd $PBS_O_WORKDIR
module load gromacs/2019.1-intel-thread-mpi-gpu
module load vmd/1.9.3

#gmx mdrun -v -ntmpi 1 -ntomp $NCPUS -deffnm memb0 -nb gpu -tunepme yes  2>&1 | tee  memb0.log
export OMP_NUM_THREADS=$NCPUS
for i in $(seq 0 15); 
do 
gmx grompp -f memb$i\.mdp -o memb$i\.tpr -c memb$i\.gro -n index.ndx -p topol.top 2>&1 | tee memb$i\_setup.log 
gmx mdrun -v -deffnm memb$i -nb gpu -tunepme yes  2>&1 | tee  memb$i\.log
last_err=$?
done

source $HOME/.bashrc
if [ ! $last_err = 0 ] ; then nsub memb1.pbs ; fi
