#!/bin/bash
#PBS -P r16
#PBS -q gpuvolta
#PBS -l ngpus=1
#PBS -l ncpus=12
#PBS -l storage=scratch/f91
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l mem=8GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2020.1-gpuvolta
#
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
gmx grompp -f memb0.mdp -o memb0.tpr -c ionized.gro -n index.ndx -p topol.top 
gmx mdrun -v -ntmpi $PBS_NGPUS -ntomp $OMP_NUM_THREADS -deffnm memb0 2>&1 
#
for i in $(seq 1 16); 
do 
gmx grompp -f memb$i\.mdp -o memb$i\.tpr -c memb$(( $i - 1 ))\.gro -r memb$(( $i - 1 ))\.gro -n index.ndx -p topol.top 
gmx mdrun -v -ntmpi $PBS_NGPUS -ntomp $OMP_NUM_THREADS -deffnm memb$i 
last_err=$?
echo $last_err 
done
#

#if the runs have finished submit the next job
source $HOME/.bashrc
if [  -f memb16.gro  ] ; then nsub memb1.pbs  ; fi
