#!/bin/bash
#PBS -P Akt_MD
#PBS -N vsite
#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -m abe
#PBS -l walltime=6:00:00
#PBS -l mem=8GB
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2020.1-intel-thread-mpi-gpu

root=$(qstat -f $PBS_JOBID | sed -rn 's/.*Resource_List.walltime = (.*)/\1/p' ) 
h=$(echo $root | awk -F: '{print $1}')
m=$(echo $root | awk -F: '{print $2}')
s=$(echo $root | awk -F: '{print $3}')
sleep_time=$(( $h*3600 + $m * 60 + $s ))
sleep_time=$( echo "$sleep_time * 0.95" |  bc -l )
h_time=$( echo "$sleep_time / 3600" | bc -l )

cd $PBS_O_WORKDIR
cp memb_prod1.log memb_prod1_backup.log

export OMP_NUM_THREADS=12
#ntmpi is equal to number of gpus
if [ -f memb_prod1.cpt ]
then
gmx mdrun -v -cpi memb_prod1.cpt -ntmpi 1 -ntomp $OMP_NUM_THREADS -deffnm memb_prod1 -maxh $h_time &
md_proc=$!
else 
	module purge
	module load gromacs/2019.1-intel
gmx grompp -f memb_prod.mdp -o memb_prod1.tpr -c memb16.gro  -n index.ndx -p topol.top 
module purge
module load gromacs/2020.1-intel-thread-mpi-gpu
gmx mdrun -v -ntmpi 1 -ntomp $OMP_NUM_THREADS -deffnm memb_prod1 -maxh $h_time &
md_proc=$!

fi 

echo $last_err
echo $sleep_time

#if the job has run for more than an hour resubmit it 

#wait till the md process has finished and if it has exitted without errors resubmit this script to restart from a checkpoint
tail --pid=$md_proc -f /dev/null
last_err=$?
wallt=$(qstat -f $PBS_JOBID | sed -rn 's/.*resources_used.walltime = (.*)/\1/p' ) 
wallt=$(echo $wallt | awk -F: '{print $1}')

source $HOME/.bashrc

if [  $wallt -gt 0 ] ; 
then 
qsub -N vsite memb1.pbs 
fi
exit 
