#!/bin/bash
#PBS -P Akt_MD
#PBS -N remembertoputsomethinghere
#PBS -l ngpus=1
#PBS -l ncpus=12
#PBS -m abe
#PBS -l walltime=12:00:00
#PBS -l mem=8GB
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2020.1-intel-thread-mpi-gpu
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
gmx grompp -f glob0.mdp -o glob0.tpr -c ionized.gro -n index.ndx -p topol.top 
gmx mdrun -v -ntmpi 1 -ntomp 12 -deffnm glob0 2>&1 

module load gromacs/2019.1-intel

gmx grompp -f glob1.mdp -o glob1.tpr -c glob0.gro -r glob0.gro -n index.ndx -p topol.top 
module purge
module load gromacs/2020.1-intel-thread-mpi-gpu

gmx mdrun -v -ntmpi 1 -ntomp 12 -deffnm glob1

module purge
last_err=$?
echo $last_err 
#

#if the runs have finished submit the next job
source $HOME/.bashrc
if [  -f glob1.gro  ] ; then qsub glob1.pbs ; fi
