#!/bin/bash
#PBS -P r16
#PBS -q gpuvolta
#PBS -l ngpus=4
#PBS -l ncpus=48
#PBS -l storage=scratch/r16
#PBS -m abe
#PBS -l walltime=12:00:00
#PBS -l mem=8GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2019.3-gpuvolta

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
if [ -f memb_prod1.cpt ]
then
gmx mdrun -v -cpi memb_prod1.cpt -ntmpi $PBS_NGPUS -ntomp $OMP_NUM_THREADS -deffnm memb_prod1 
else 
gmx mdrun -v -ntmpi $PBS_NGPUS -ntomp $OMP_NUM_THREADS -deffnm memb_prod1 
fi 

last_err=$?
echo $last_err


source $HOME/.bashrc
if [  $last_err = 0 ] ; then nsub memb1.pbs ; fi
