#!/bin/bash
#PBS -P r16
#PBS -q gpuvolta
#PBS -l ngpus=4
#PBS -l ncpus=48
#PBS -l storage=scratch/r16
#PBS -m abe
#PBS -l walltime=12:00:00
#PBS -l mem=8GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2019.3-gpuvolta

root=$(qstat -f $PBS_JOBID | sed -rn 's/.*Resource_List.walltime = (.*)/\1/p' ) 
h=$(echo $root | awk -F: '{print $1}')
m=$(echo $root | awk -F: '{print $2}')
s=$(echo $root | awk -F: '{print $3}')
sleep_time=$(( $h*3600 + $m * 60 + $s ))
sleep_time=$( echo "$sleep_time * 0.95" |  bc -l )
h_time=$( echo "$sleep_time / 3600" | bc -l )

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
if [ -f memb_prod2.cpt ]
then
gmx mdrun -v -cpi memb_prod2.cpt -ntmpi $PBS_NGPUS -ntomp $OMP_NUM_THREADS -deffnm memb_prod2 -maxh $h_time &
md_proc=$!
else 
gmx grompp -f memb_prod.mdp -o memb_prod2.tpr -c memb_prod1.gro -t memb_prod1.cpt -n index.ndx -p topol.top 
gmx mdrun -v -ntmpi $PBS_NGPUS -ntomp $OMP_NUM_THREADS -deffnm memb_prod2 -maxh $h_time &
md_proc=$!

fi 

echo $last_err
echo $sleep_time

#if the job has run for more than an hour resubmit it 

#wait till the md process has finished and if it has exitted without errors resubmit this script to restart from a checkpoint
tail --pid=$md_proc -f /dev/null
last_err=$?
wallt=$(qstat -f $PBS_JOBID | sed -rn 's/.*resources_used.walltime = (.*)/\1/p' ) 
wallt=$(echo $wallt | awk -F: '{print $1}')

source $HOME/.bashrc

if [  $wallt > 0 ] ; 
then 
nsub memb2.pbs 
fi
exit 
