#!/bin/bash
#PBS -P r16
#PBS -q gpuvolta
#PBS -l ngpus=4
#PBS -l ncpus=48
#PBS -l storage=scratch/r16
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l mem=8GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2019.3-gpuvolta
#
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
gmx grompp -f memb0.mdp -o memb0.tpr -c ionized.gro -n index.ndx -p topol.top 2>&1 | tee memb0_setup.log 
gmx mdrun -v -ntmpi $PBS_NGPUS -ntomp 12 -deffnm memb0 2>&1 | tee memb0.log
#
for i in $(seq 1 16); 
do 
gmx grompp -f memb$i\.mdp -o memb$i\.tpr -c memb$(( $i - 1 ))\.gro -r memb$(( $i - 1 ))\.gro -n index.ndx -p topol.top 2>&1 | tee memb$i\_setup.log 
gmx mdrun -v -ntmpi $PBS_NGPUS -ntomp 12 -deffnm memb$i 2>&1 | tee memb$i\.log
last_err=$?
echo $last_err 
done
#
gmx grompp -f memb_prod.mdp -o memb_prod1.tpr -c memb16.gro -n index.ndx -p topol.top 


source $HOME/.bashrc
if [  $last_err = 0 ] ; then nsub memb1.pbs ; fi
