#!/bin/bash
#PBS -P r16
#PBS -q normal
#PBS -l ncpus=2
#PBS -l storage=scratch/r16
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l mem=16GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2019.3

mkdir -p ../xtcs/
for i in $(cat /scratch/r16/ma2374/gmx_cftr_2nd_round/misc_scripts/list);
do 
cd $i
pwd
file_name=$(echo $i | sed "s^\/^_^g")
cp ionized.psf /scratch/r16/ma2374/gmx_cftr_2nd_round/xtcs/$file_name.psf
#gmx trjcat -f memb_prod*.trr -o all.xtc -dt 1000
membs=$(ls -v  memb_prod*xtc | tail -n 1 )
echo $membs
echo -e "1\n0\n" | gmx trjconv  -center -ndec 3 -f $membs -s memb0.tpr -o $PBS_O_WORKDIR/../xtcs/$file_name.xtc -dt 1000 -pbc nojump
cp $membs /scratch/r16/ma2374/gmx_cftr_2nd_round/xtcs/$file_name.xtc

done 
