#!/bin/bash
#PBS -P r16
#PBS -q normal
#PBS -l ncpus=2
#PBS -l storage=scratch/f91
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l mem=16GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2021
cd $PBS_O_WORKDIR

pwd
membs=$(ls -v  memb_prod*xtc | tail -n 1 )
echo $membs
echo -e "0\n" | gmx trjconv -f $membs -s memb0.tpr -o sum\_temp1.xtc -pbc whole -dt 1000 
echo -e "1\n1\n0\n" | gmx trjconv -center yes  -f sum\_temp1.xtc -s memb0.tpr -o sum\_temp2.xtc -pbc cluster
rm sum\_temp1.xtc

echo -e "1\n0\n" | gmx trjconv -f sum\_temp2.xtc  -s memb0.tpr -o sum\_temp3.xtc -pbc res -center yes
rm sum\_temp2.xtc 

echo -e "1\n1\n0\n" | gmx trjconv -f sum\_temp3.xtc   -s memb0.tpr -o sum\_temp4.xtc -pbc cluster -center yes 

rm sum\_temp3.xtc

echo -e "1\n0\n" | gmx trjconv -f sum\_temp4.xtc -o sum.xtc -center yes -n index.ndx -pbc mol -s memb0.tpr
echo -e "0\n" | gmx trjconv  -f sum.xtc -dt 1000   -o sum\_sum.xtc 
rm sum\_temp4.xtc

source $HOME/.bashrc

rm \#sum.xtc\#
rm \#sum_sum.xtc\#
