#!/bin/bash
#PBS -P r16
#PBS -q normal
#PBS -l ncpus=2
#PBS -l storage=scratch/f91+scratch/r16
#PBS -m abe
#PBS -l walltime=48:00:00
#PBS -l mem=16GB
#PBS -l wd
#PBS -M yearlyboozefest@gmail.com

module load gromacs/2020.1
#cd $PBS_O_WORKDIR

echo -e "1\n0" | gmx trjconv -f glob_prod1.xtc -s glob0.tpr -pbc whole -center yes  -o glob_temp.xtc -dt 1000
rm glob_temp.xtc
echo -e "1\n1\n0" | gmx trjconv -f glob_prod1.xtc -s glob0.tpr -pbc cluster -center yes  -o sum.xtc

rm \#*\#
